apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-service
  template:
    metadata:
      labels:
        app: address-service
    spec:
      containers:
      - name: address-service
        image: 102789521217.dkr.ecr.us-east-1.amazonaws.com/bank-service
        ports:
        - containerPort: 80
