apiVersion: v1
kind: Service
metadata:
  name: bank-service 
  labels:
    name: bank-service   
spec:
  ports:
    - port: 8083
  selector:
    app: bank-service
  type: NodePort
© 2020 GitHub, Inc.
